//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livetock_Farm_Management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myfarmEntities : DbContext
    {
        public myfarmEntities()
            : base("name=myfarmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customerType> customerTypes { get; set; }
        public virtual DbSet<deadPig> deadPigs { get; set; }
        public virtual DbSet<fieldState> fieldStates { get; set; }
        public virtual DbSet<input> inputs { get; set; }
        public virtual DbSet<outSourcedPig> outSourcedPigs { get; set; }
        public virtual DbSet<pigRelationship> pigRelationships { get; set; }
        public virtual DbSet<pig> pigs { get; set; }
        public virtual DbSet<pigSource> pigSources { get; set; }
        public virtual DbSet<pigState> pigStates { get; set; }
        public virtual DbSet<productType> productTypes { get; set; }
        public virtual DbSet<sale> sales { get; set; }
        public virtual DbSet<sex> sexes { get; set; }
        public virtual DbSet<sickPig> sickPigs { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<systemRole> systemRoles { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<vaccination> vaccinations { get; set; }
        public virtual DbSet<vaccineType> vaccineTypes { get; set; }
    }
}
