//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livetock_Farm_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pig()
        {
            this.deadPigs = new HashSet<deadPig>();
            this.inputs = new HashSet<input>();
            this.outSourcedPigs = new HashSet<outSourcedPig>();
            this.pigRelationships = new HashSet<pigRelationship>();
            this.pigRelationships1 = new HashSet<pigRelationship>();
            this.pigRelationships2 = new HashSet<pigRelationship>();
            this.sales = new HashSet<sale>();
            this.sickPigs = new HashSet<sickPig>();
            this.vaccinations = new HashSet<vaccination>();
        }
    
        public int pigNumber { get; set; }
        public string tagNumber { get; set; }
        public int pigSex { get; set; }
        public string pigColor { get; set; }
        public string description { get; set; }
        public int status { get; set; }
        public System.DateTime dateOfAcquisition { get; set; }
        public string approximateAgeInYears { get; set; }
        public string approximateAgeInMonths { get; set; }
        public int source { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deadPig> deadPigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<input> inputs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<outSourcedPig> outSourcedPigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pigRelationship> pigRelationships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pigRelationship> pigRelationships1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pigRelationship> pigRelationships2 { get; set; }
        public virtual pigSource pigSource { get; set; }
        public virtual pigState pigState { get; set; }
        public virtual sex sex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale> sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sickPig> sickPigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vaccination> vaccinations { get; set; }
    }
}
