//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livetock_Farm_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int salesID { get; set; }
        public int pigNumber { get; set; }
        public decimal price { get; set; }
        public System.DateTime salesDate { get; set; }
        public int customerID { get; set; }
        public int userID { get; set; }
        public int status { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual fieldState fieldState { get; set; }
        public virtual pig pig { get; set; }
        public virtual user user { get; set; }
    }
}
