//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Livetock_Farm_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sickPig
    {
        public int SicknessID { get; set; }
        public int pigNumber { get; set; }
        public System.DateTime dateRecorded { get; set; }
        public string sicknessDescription { get; set; }
        public System.DateTime recoveryDate { get; set; }
        public int status { get; set; }
    
        public virtual pig pig { get; set; }
        public virtual pigState pigState { get; set; }
    }
}
